version: "3"
services:
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: wiremock
    ports:
      - 3001:8080
    volumes:
      - ./docker/wiremock:/home/wiremock
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
volumes:
  cache:
    driver: local