package com.aterrizar.service.payment.facade;

import com.aterrizar.service.payment.model.PaymentRequestDto;

public interface PaymentFacade {
    /**
     * Orchestrates the retrieval of the appropriate adapter and the processing of the payment.
     *
     * @return the paymentToken generated by the external mock.
     */
    String executePayment(PaymentRequestDto request);
}
