openapi: 3.1.0
info:
  title: Country Code Schema
  version: 1.0.0
components:
  schemas:
    VeCheckinRequestData:
      type: object
      properties:
        sessionId:
          type: string
          required: true
          format: uuid
        userId:
          type: string
          required: true
          format: uuid
        country:
          $ref: './shared.yaml#/components/schemas/CountryCode'
        providedFields:
          type: object
          additionalProperties:
            type: string
          description: A map of required fields and their corresponding values.
